#!/usr/bin/env bash

## Description: Run project's Codesniffer inspections.
## Usage: cs
## Example: "ddev cs"

./vendor/bin/phpcs \
  --standard=Drupal,DrupalPractice \
  --extensions=php,module,inc,install,test,profile,theme,info \
  ./web/modules/custom
